stages:
  - InstallDependencies
  - CheckLicenses

install_dependencies:
  stage: InstallDependencies
  image: node:alpine
  script:
    - npm ci
  artifacts:
    paths:
      - ./node_modules
  only:
    - merge_requests
# Check licenses in Web package
check_licenses:
  stage: CheckLicenses
  image: node:alpine
  script:
    - yarn add -D danger @brainhubeu/license-auditor
    - yarn danger ci --verbose --id Web
  variables:
    DANGER_GITLAB_API_TOKEN: $DANGER_GITLAB_API_TOKEN # Gitlab Access Token stored in Gitlab env variable.
    PROJECT_PATH: . # Relative to dangerfile/project root
  only:
    - merge_requests
