name: Pull Request
on: [pull_request]
jobs:
  LicenseCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn
      - name: Check licenses
        run: |
          yarn add -D danger
          yarn danger ci --failOnErrors --verbose --id LicenceAuditor
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PROJECT_PATH: "."
